name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t test-image .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Tag Docker image as latest
        run: docker tag test-image "naasirosman/test-repo:latest"

      - name: Tag Docker image with git commit sha
        run: docker tag test-image "naasirosman/test-repo:${{ github.sha }}"

      - name: Push Docker image
        run: |
          docker push "naasirosman/test-repo:latest"
          docker push "naasirosman/test-repo:${{ github.sha }}"

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker Image Update on Azure
        run: |
          az webapp config container set --resource-group docker-task-rg --name docke-web-app3 --docker-custom-image-name ${{ secrets.DOCKER_HUB_USERNAME }}/azure:${{ github.sha }}

  security-scan:
    needs: [build-and-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "naasirosman/test-repo:${{ github.sha }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
